global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus_main:9090
  
  - job_name: nodes
    scrape_interval: 5s
    static_configs:
    - targets:
      - 192.168.50.4:9100
      - 192.168.50.5:9100
      - 192.168.50.6:9100
  
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 192.168.50.4:8081
      - 192.168.50.5:8081
      - 192.168.50.6:8081

